stages:          # List of stages for jobs, and their order of execution
  - build
  - test

.job_template: &job_config
  image: python:3.9
  services:
    - postgres

build-job:        # This job runs in the build stage, which runs first.
  <<: *job_config
  stage: build
  script:
    - pip install pipenv
    - pipenv sync -d
    - cp contrib/env-sample .env

test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  before_script:
    - psql -c "CREATE DATABASE testdb;" -U postgres
  script:
    - pipenv run flake8 .
    - pipenv run pytest --cov=pypro
  after_script:
    - pipenv run codecov

